export enum Genres {
  Music = 'KZFzniwnSyZfZ7v7nJ',
  Other = 'KnvZfZ7vAvl',
  Rock = 'KnvZfZ7vAeA',
  DanceElectronic = 'KnvZfZ7vAvF',
  HipHopRap = 'KnvZfZ7vAv1',
  Folk = 'KnvZfZ7vAva',
  Pop = 'KnvZfZ7vAev',
  Alternative = 'KnvZfZ7vAvv',
  Metal = 'KnvZfZ7vAvt',
  Blues = 'KnvZfZ7vAvd',
  Reggae = 'KnvZfZ7vAed',
  RB = 'KnvZfZ7vAee',
  World = 'KnvZfZ7vAeF',
  Jazz = 'KnvZfZ7vAvE',
  Classical = 'KnvZfZ7vAeJ',
}
