# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - spotifyxtickets-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_8c1eec8fbaf547ca9e2463f781116303 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ebf504175cb24f41a3d345c89c3e72a4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8c1eec8fbaf547ca9e2463f781116303 }}/3739323298328/spotify-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'spotifyxtickets-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2bf86f8ad91a4e01ad45902a1b924359 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8c1eec8fbaf547ca9e2463f781116303 }}/3739323298328/spotify-api:${{ github.sha }}'