# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - spotifyxtickets-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_85f5f3d1434d426398d61169cbac4f6e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ff22bc87c75a4be0a83237e6e3bad42c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_85f5f3d1434d426398d61169cbac4f6e }}/spotify-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'spotifyxtickets-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_32d067f58dbc4b2197da67762fc1a574 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_85f5f3d1434d426398d61169cbac4f6e }}/spotify-api:${{ github.sha }}'